export const films = [
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
  {
    id: 3,
    preview: "film3",
    previewAlt: "Walter White olhando para frente com uma cara de desconfiado",
    title: "Breaking Bad",
    relevant: "98% relevante",
    duration: "5 temporadas",
  },
  {
    id: 1,
    preview: "film1",
    previewAlt: "Vários pandas deitados num lago",
    title: "Kung Fu Panda 3",
    relevant: "95% relevante",
    duration: "1h 34min",
  },
  {
    id: 2,
    preview: "film2",
    previewAlt: "Ragnar olhando fixamente para frente",
    title: "Vikings",
    relevant: "97% relevante",
    duration: "6 temporadas",
  },
];

export const slides = [
  {
    id: 1,
    img: "army",
    title: "armylogo",
    text: "Após um surto de zumbis em Las Vegas, um grupo de mercenários se aventura em uma zona de quarentena para tentar realizar o maior assalto de todos os tempos.",
  },

  {
    id: 2,
    img: "rm",
    title: "rmlogo",
    text: "O brilhante cientista beberrão Rick sequestra Morty, seu neto aborrecente, para viver loucuras em outros mundos e dimensões alternativas.",
  },

  {
    id: 3,
    img: "st",
    title: "stlogo_2",
    text: "No caminho de volta para casa, Will é aterrorizado por alguma coisa. Não longe dali, um laboratório secreto guarda um segredo sinistro.",
  },
];

// export default slides;
// export default films;
